#!/bin/bash
rm -f result
chmod +x ./Grade01
chmod +x ./testfiles/sol.exe

corr=0;

for i in `seq 1 10`; do
    rm -f tempresult1
    rm -f tempresult2 
    ./MergeInsertion.exe < ./testfiles/t$i >> tempresult1
    ./testfiles/sol.exe < ./testfiles/t$i >> tempresult2
    diff tempresult1 tempresult2 >> tempcnt
    if [ -s tempcnt ] ; then
      echo "test $i: fail"
      echo "test $i: fail" >> result
    else
      echo "test $i: success"
      echo "test $i: success" >> result
      ((corr=corr+1))
    fi;
done

echo "score: $corr";
echo $(whoami) "score: ${corr}" >> result

rm -f tempresult1
rm -f tempresult2
rm -f tempcnt

